version: '3'

# docker-compose exec nodered npm install node-red-node-sqlite node-red-contrib-postgres

# access 172.18.0.100:8000


networks:
  sdosnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  sdos:
    build: ./docker-sdos
    image: mcm/sdos
    environment:
      - MY_ENDPOINT_HOST=172.18.0.11
      - SWIFT_AUTH_VERSION=${SWIFT_AUTH_VERSION:-1.0}
      - SWIFT_AUTH_HOST=${SWIFT_AUTH_HOST:-172.18.0.22}
      - SWIFT_AUTH_PORT=${SWIFT_AUTH_PORT:-8080}
      - SWIFT_STORE_HOST=${SWIFT_STORE_HOST:-172.18.0.22}
      - SWIFT_STORE_PORT=${SWIFT_STORE_PORT:-8080}
    ports:
      - "3000:3000"
    networks:
      sdosnet:
        ipv4_address: 172.18.0.11

  bluebox:
    build: ./docker-bluebox
    image: mcm/bluebox
    environment:
      - MY_ENDPOINT_HOST=${PUBLIC_HOST:-localhost}
      - SWIFT_AUTH_VERSION=${SWIFT_AUTH_VERSION:-1.0}
      - SWIFT_HOST=172.18.0.11
      - SWIFT_PORT=3000
      - POSTGRES_HOST=172.18.0.44
      - NODERED_HOST=172.18.0.55
    ports:
      - "8000:8000"
    networks:
      sdosnet:
        ipv4_address: 172.18.0.100

  extractor:
    build: ./docker-extractor
    image: mcm/extractor
    environment:
      - TENANT_NAME=${TENANT_NAME:-mcmdemo}
      - SWIFT_HOST=172.18.0.11
      - SWIFT_PORT=3000
      - KAFKA_HOST=172.18.0.33
      - POSTGRES_HOST=172.18.0.44
    networks:
      - sdosnet





####### swift storage backend
  swift:
    build: ./docker-swift
    image: mcm/swift
    volumes:
      - ${SWIFT_STORE_PATH:-/tmp/mcm_swift}:/srv
    ports:
      - "8080:8080"
    networks:
      sdosnet:
        ipv4_address: 172.18.0.22

####### ceph storage backend
# to later configure ceph:
# docker-compose exec ceph radosgw-admin subuser create --uid=sdos --subuser=sdos:user --access=full
# docker-compose exec ceph radosgw-admin key create --subuser=sdos:user --key-type=swift --gen-secret
#  ceph:
#    image: ceph/demo
#    #volumes:
#      #- /mnt________:/var/lib/ceph
#      #- /etc/ceph:/etc/ceph
#    environment:
#      - MON_IP=172.18.0.22
#      - CEPH_PUBLIC_NETWORK=172.18.0.0/24
#      - CEPH_DEMO_UID=sdos
#      - CEPH_DEMO_ACCESS_KEY="passw0rd"
#      - CEPH_DEMO_SECRET_KEY="passw0rd"
#    networks:
#      sdosnet:
#        ipv4_address: 172.18.0.22

####### external images for db/messaging/nodered
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=mcm_metadata_${TENANT_NAME:-mcmdemo}
    ports:
      - "5432:5432"
    networks:
      sdosnet:
        ipv4_address: 172.18.0.44
  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_HOST=172.18.0.33
      - ADVERTISED_PORT=9092
    ports:
      - "9092:9092"
      - "2181:2181"
    networks:
      sdosnet:
        ipv4_address: 172.18.0.33
  msg_spooler:
    build: https://github.com/sdos/kafka-websocket.git
    ports:
      - "31780:7080"
    networks:
      - sdosnet

  nodered:
    build: https://github.com/sdos/node-red-docker.git#:latest
    ports:
      - "31880:1880"
    networks:
      sdosnet:
        ipv4_address: 172.18.0.55



