version: '3'

# docker-compose exec nodered npm install node-red-node-sqlite node-red-contrib-postgres

# access 172.18.0.100:8000


networks:
  sdosnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  sdos:
    image: sdos-core:latest
    environment:
      - MY_ENDPOINT_HOST=172.18.0.11
      - SWIFT_AUTH_VERSION=${SWIFT_AUTH_VERSION:-1.0}
      - SWIFT_AUTH_HOST=${SWIFT_AUTH_HOST:-172.18.0.22}
      - SWIFT_AUTH_PORT=${SWIFT_AUTH_PORT:-8080}
      - SWIFT_STORE_HOST=${SWIFT_STORE_HOST:-172.18.0.22}
      - SWIFT_STORE_PORT=${SWIFT_STORE_PORT:-8080}
    ports:
      - "3000:3000"
    networks:
      sdosnet:
        ipv4_address: 172.18.0.11

  bluebox:
    image: bluebox-webui:latest
    environment:
      - MY_ENDPOINT_HOST=${PUBLIC_HOST:-localhost}
      - SWIFT_AUTH_VERSION=${SWIFT_AUTH_VERSION:-1.0}
      - SWIFT_HOST=172.18.0.11
      - SWIFT_PORT=3000
      - POSTGRES_HOST=172.18.0.44
      - NODERED_HOST=172.18.0.55
    ports:
      - "8000:8000"
    networks:
      sdosnet:
        ipv4_address: 172.18.0.100

####### swift storage backend
  swift:
    image: docker.io/morrisjobke/docker-swift-onlyone:latest
#    volumes:
#      - ${SWIFT_STORE_PATH:-/tmp/mcm_swift}:/srv
    ports:
      - "8080:8080"
    networks:
      sdosnet:
        ipv4_address: 172.18.0.22
